#!/usr/bin/env python3
"""Generate the fabricated-board pin table inside PCB_COMPONENTS.md.

The PCB document has to answer one question accurately: *which FPGA pin goes to
which net*.  That mapping already exists exactly once, in
`constraints/ecp5_144tqfp.lpf` — the same file the bitstream is built from — so
this script reads it and writes the table between two markers, rather than
letting a second copy drift.

    scripts/sv16_pcb_doc.py            # regenerate the block in PCB_COMPONENTS.md
    scripts/sv16_pcb_doc.py --check    # exit 1 if the file is stale (used by make lint)
    scripts/sv16_pcb_doc.py --csv FILE # also write a Pin,Signal,Bank,Type,Pull,Drive CSV

The table lists the ports the design actually constrains (52 today).  The other
46 I/O pins are unassigned and appear in the full 144-pin table in
`board/TQFP144_PINOUT.md`, which is generated by `scripts/sv16_board_pins.py`.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LPF = ROOT / "constraints" / "ecp5_144tqfp.lpf"
PINS_JSON = ROOT / "board" / "ecp5_tqfp144.json"
DOC = ROOT / "PCB_COMPONENTS.md"

BEGIN = "<!-- BEGIN U1-PIN-TABLE (generated by scripts/sv16_pcb_doc.py from constraints/ecp5_144tqfp.lpf) -->"
END = "<!-- END U1-PIN-TABLE -->"

# what each constrained port is for, on the board — matches BOARD.md section 6.1
DESTINATION = {
    "clk_25m": "Y1.3 (25 MHz oscillator output)",
    "ext_rst_n": "SW1 + R1 + C1 (reset button)",
    "uart_rx": "U4 TXD via R21 (or J10.3 via R22)",
    "uart_tx": "U4 RXD via R23 (or J10.2 via R24)",
    "flash_sck": "U3.6 CLK (application flash)",
    "flash_cs_n": "U3.1 /CS",
    "flash_mosi": "U3.5 DI",
    "flash_miso": "U3.2 DO",
    "spi0_sck": "J3.12 (EXP-A)",
    "spi0_cs_n": "J3.11 (EXP-A)",
    "spi0_mosi": "J3.13 (EXP-A)",
    "spi0_miso": "J3.14 (EXP-A)",
    "pwm_out": "J6.3 (motor PWM)",
    "motor_dir1": "J6.4 (motor DIR1)",
    "motor_dir2": "J6.5 (motor DIR2)",
    "motor_fault_n": "J6.6 (motor FAULTn) + R19 pull-up",
}


def board_net(signal: str) -> str:
    if signal in DESTINATION:
        return DESTINATION[signal]
    if signal.startswith("led["):
        index = signal[signal.index("[") + 1:signal.index("]")]
        return "D%d + R%d (status LED, active low)" % (int(index) + 2, 27 + int(index))
    if signal.startswith("gpio_a["):
        index = int(signal[signal.index("[") + 1:signal.index("]")])
        if index <= 7:
            return "J5.%d (EXP-C)%s" % (index + 1,
                                        " + U2 config-flash net (BOARD.md 6.4)"
                                        if index in (1, 2, 4, 6) else "")
        return "J3.%d (EXP-A)" % (index - 5)   # J3.3 = A8, J3.10 = A15
    if signal.startswith("gpio_b["):
        index = int(signal[signal.index("[") + 1:signal.index("]")])
        return "J4.%d (EXP-B)" % (index + 3)   # J4.3 = B0, J4.18 = B15
    return ""


def parse_lpf() -> list[dict]:
    sites: dict[str, str] = {}
    attrs: dict[str, dict] = {}
    order: list[str] = []
    for line in LPF.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        match = re.match(r'LOCATE\s+COMP\s+"([^"]+)"\s+SITE\s+"([^"]+)"', line)
        if match:
            sites[match.group(1)] = match.group(2)
            order.append(match.group(1))
            continue
        match = re.match(r'IOBUF\s+PORT\s+"([^"]+)"\s+(.*);', line)
        if match:
            attrs[match.group(1)] = dict(
                token.split("=", 1) for token in match.group(2).split() if "=" in token)
    ports = []
    for signal in sites:
        attr = attrs.get(signal, {})
        ports.append({
            "signal": signal,
            "pin": sites[signal],
            "io_type": attr.get("IO_TYPE", "LVCMOS33"),
            "drive": attr.get("DRIVE", "4"),
            "pull": attr.get("PULLMODE", "NONE"),
        })
    return ports


def render(ports: list[dict]) -> str:
    pins = json.loads(PINS_JSON.read_text())["pins"]
    bank_of = {pin: info.get("bank", "—") for pin, info in pins.items()}

    rows = sorted(ports, key=lambda p: int(p["pin"]))
    lines = [
        BEGIN.rstrip(),
        "",
        "| TQFP pin | Bank | Port (LPF name) | IO type | Drive | Pull | Board net |",
        "| ---: | :-: | :--- | :--- | ---: | :--- | :--- |",
    ]
    for port in rows:
        lines.append("| %s | %s | `%s` | %s | %s mA | %s | %s |"
                     % (port["pin"], bank_of.get(port["pin"], "?"), port["signal"],
                        port["io_type"], port["drive"], port["pull"],
                        board_net(port["signal"]) or "—"))
    lines += ["", "_%d constrained ports. Bank numbers come from "
              "`board/ecp5_tqfp144.json`; every bank on this board is 3V3 "
              "(VCCIO8 = 3V3 for the configuration and JTAG domains)._"
              % len(rows), "", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if PCB_COMPONENTS.md has a stale pin table")
    ap.add_argument("--csv", default=None, help="also write a CSV of the table")
    args = ap.parse_args()

    ports = parse_lpf()
    block = render(ports)

    if args.csv:
        pins = json.loads(PINS_JSON.read_text())["pins"]
        with open(args.csv, "w", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(["pin", "bank", "signal", "io_type", "drive_ma", "pull", "board_net"])
            for port in sorted(ports, key=lambda p: int(p["pin"])):
                writer.writerow([port["pin"], pins.get(port["pin"], {}).get("bank", ""),
                                 port["signal"], port["io_type"], port["drive"],
                                 port["pull"], board_net(port["signal"])])
        print("wrote %s (%d ports)" % (args.csv, len(ports)))

    text = DOC.read_text()
    if BEGIN not in text or END not in text:
        print("ERROR: markers not found in %s" % DOC.relative_to(ROOT), file=sys.stderr)
        return 2
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    refreshed = head + block + tail

    if args.check:
        if refreshed != text:
            print("ERROR: %s pin table is stale - run scripts/sv16_pcb_doc.py"
                  % DOC.relative_to(ROOT), file=sys.stderr)
            return 1
        print("%s pin table is up to date (%d ports)" % (DOC.name, len(ports)))
        return 0

    if refreshed != text:
        DOC.write_text(refreshed)
        print("updated %s (%d constrained ports)" % (DOC.relative_to(ROOT), len(ports)))
    else:
        print("%s already up to date (%d ports)" % (DOC.relative_to(ROOT), len(ports)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
