#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# SV-16 — bitstream flow: Yosys (synthesis) -> nextpnr-ecp5 (P&R) -> ecppack.
#
#   source scripts/sv16_venv.sh
#   scripts/sv16_synth.sh                 # full flow into build/
#   scripts/sv16_synth.sh --no-rom        # synthesize with an empty boot ROM
#   scripts/sv16_synth.sh --clkdiv 2      # build the 12.5 MHz (timing-clean) SoC
#   scripts/sv16_synth.sh --freq 40       # different timing target
#
# The boot ROM contents are compiled into the bitstream: the ROM's init file is
# a synthesis-time macro (SV16_ROM_INIT_FILE), so the monitor that comes up on
# a fresh device is exactly build/rom/monitor.hex.  `make firmware` builds it;
# this script refuses to run without it unless --no-rom is given.
#
# Outputs (in --out, default build/):
#   sv16_top.json     synthesized netlist (Yosys)
#   sv16_top.config   placed and routed configuration (nextpnr-ecp5, Trellis)
#   sv16_top.bit      bitstream for the device (ecppack --compress)
#   sv16_top.timing.json  timing/utilization report (nextpnr-ecp5 --report)
#   sv16_synth.ys     the Yosys script that was run (kept for reproducibility)
# ---------------------------------------------------------------------------
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

out="build"
rom="build/rom/monitor.hex"
lpf="constraints/ecp5_144tqfp.lpf"
freq=""
device="--12k"
package="TQFP144"
speed="6"
top="sv16_top"
unconstrained=""
yosys_only=""
clkdiv="1"

while [ $# -gt 0 ]; do
    case "$1" in
        --out)     out="$2"; shift 2 ;;
        --rom)     rom="$2"; shift 2 ;;
        --lpf)     lpf="$2"; shift 2 ;;
        --freq)    freq="$2"; shift 2 ;;
        --clkdiv)  clkdiv="$2"; shift 2 ;;
        --speed)   speed="$2"; shift 2 ;;
        --top)     top="$2"; shift 2 ;;
        --no-rom)  rom=""; shift ;;
        --yosys-only) yosys_only="1"; shift ;;
        --lpf-allow-unconstrained) unconstrained="--lpf-allow-unconstrained"; shift ;;
        -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

for tool in yosys nextpnr-ecp5 ecppack; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "$tool not found — run: source scripts/sv16_venv.sh" >&2
        exit 1
    }
done

if [ -n "$rom" ] && [ ! -f "$rom" ]; then
    echo "$rom not found — run: make firmware   (or --no-rom)" >&2
    exit 1
fi

mkdir -p "$out"

# Read order matters to Yosys: the package first (the rest import its
# constants), then the modules, then the SoC top (which defines the ROM init
# macro and is the synthesis top).
mapfile -t rtl_files < <(ls rtl/*.sv | grep -vE 'sv16_(pkg|top)\.sv$')
rtl_files=(rtl/sv16_pkg.sv "${rtl_files[@]}" rtl/sv16_top.sv)

ys="$out/sv16_synth.ys"

# The ROM contents are a Verilog macro, so the boot image is compiled into the
# bitstream.  It is supplied through a generated header instead of a `-D` on the
# command line: the path is then a normal Verilog string literal and no shell or
# Yosys-script quoting is involved.
if [ -z "$freq" ]; then
    freq=$(( 25 / clkdiv ))
fi

defines="$out/sv16_defines.svh"
{
    if [ -n "$rom" ]; then
        printf '`define SV16_ROM_INIT_FILE "%s"\n' "$rom"
    else
        printf '`define SV16_ROM_INIT_FILE ""\n'
    fi
    printf '`define SV16_CLKDIV %s\n' "$clkdiv"
} > "$defines"

{
    echo "# generated by scripts/sv16_synth.sh — do not edit"
    echo "verilog_defines -DSYNTHESIS"
    echo "read_verilog -sv $defines ${rtl_files[*]}"
    echo "hierarchy -top $top"
    echo "synth_ecp5 -top $top -json $out/$top.json"
} > "$ys"

echo "[sv16] synthesizing $top: LFE5U-12F-$speed $package, ${freq} MHz system clock (ROM: ${rom:-<empty>})"
yosys -q -l "$out/sv16_yosys.log" -s "$ys"
if grep -qiE "warning: unable to (open|find).*monitor|failed to open" "$out/sv16_yosys.log"; then
    echo "[sv16] the boot ROM init file could not be read by Yosys:" >&2
    grep -iE "warning|error" "$out/sv16_yosys.log" >&2
    exit 1
fi
grep -E "Number of cells|Number of wire bits|EBR|LUT4" "$out/sv16_yosys.log" \
    | tail -6 | sed 's/^/[sv16] /'

if [ -n "$yosys_only" ]; then
    echo "[sv16] synthesis only (--yosys-only): $out/$top.json"
    exit 0
fi

echo "[sv16] placing and routing (pin constraints: $lpf)"
nextpnr-ecp5 $device --package "$package" --speed "$speed" --freq "$freq" \
    --json "$out/$top.json" --lpf "$lpf" $unconstrained \
    --textcfg "$out/$top.config" --report "$out/$top.timing.json" \
    --log "$out/sv16_nextpnr.log"
grep -E "Info: (Device utilisation|Max frequency|Critical path report)|WARNING|ERROR" \
    "$out/sv16_nextpnr.log" | tail -12 | sed 's/^/[sv16] /'
if grep -qE "^\s*Warning|ERROR" "$out/sv16_nextpnr.log"; then
    echo "[sv16] --- nextpnr warnings ---"
    grep -E "^\s*Warning|ERROR" "$out/sv16_nextpnr.log" | sed 's/^/[sv16] /'
fi

echo "[sv16] packing the bitstream"
ecppack --compress "$out/$top.config" "$out/$top.bit"
ls -l "$out/$top.bit" | awk '{print "[sv16] bitstream: " $9 " (" $5 " bytes)"}'
echo "[sv16] done — program it with: make prog"
